version: '3.1'

services:
  rabbitmq_almoxarifado:
    image: rabbitmq:management
    container_name: rabbitmq_almoxarifado
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
